### ISSUE TITLE
myapp-1   docker 运行启动后，不断重启

### ISSUE THREAD

**Issue by theseusyang1** [tencentmusic/cube-studio#117]
myapp-1 ccr.ccs.tencentyun.com/cube-studio/kubeflow-dashboard:2022.09.01
Restarting (1)

Traceback (most recent call last):
  File "/home/myapp/myapp/bin/myapp", line 4, in <module>
    from myapp.cli import create_app
  File "/home/myapp/myapp/__init__.py", line 331, in <module>
    from myapp import views
  File "/home/myapp/myapp/views/__init__.py", line 7, in <module>
    from . import view_docker
  File "/home/myapp/myapp/views/view_docker.py", line 77, in <module>
    class Docker_ModelView_Base():
  File "/home/myapp/myapp/views/view_docker.py", line 119, in Docker_ModelView_Base
    description=Markup(f'基础镜像和构建方法可参考：<a href="%s">点击打开</a>'%(conf.get('HELP_URL').get('docker',''))),
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by data-infra** [comment]
docker-compose down
