### ISSUE TITLE
单机部署 myapp/home 无法进入

### ISSUE THREAD

**Issue by tshark** [tencentmusic/cube-studio#145]
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in handle_user_exception
    return self.handle_http_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1743, in handle_http_exception
    return handler(e)
  File "/home/myapp/myapp/__init__.py", line 324, in page_not_found
    "404.html", base_template=appbuilder.base_template, appbuilder=appbuilder
  File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/myapp/myapp/templates/404.html", line 1, in top-level template code
    {% extends "appbuilder/base.html" %}
  File "/usr/local/lib/python3.6/dist-packages/flask_appbuilder/templates/appbuilder/base.html", line 1, in top-level template code
    {% extends base_template %}
  File "/home/myapp/myapp/templates/myapp/base.html", line 1, in top-level template code
    {% extends "appbuilder/baselayout.html" %}
  File "/home/myapp/myapp/templates/appbuilder/baselayout.html", line 2, in top-level template code
    {% import 'appbuilder/baselib.html' as baselib %}
  File "/home/myapp/myapp/templates/appbuilder/init.html", line 47, in top-level template code
    {% block body %}
  File "/home/myapp/myapp/templates/appbuilder/baselayout.html", line 9, in block "body"
    {% block navbar %}
  File "/home/myapp/myapp/templates/appbuilder/baselayout.html", line 11, in block "navbar"
    {% include 'appbuilder/navbar.html' %}
  File "/home/myapp/myapp/templates/appbuilder/navbar.html", line 29, in top-level template code
    {% include 'appbuilder/navbar_menu.html' %}
  File "/home/myapp/myapp/templates/appbuilder/navbar_menu.html", line 11, in top-level template code
    {% if item1 and security_manager.can_access("menu_access",item1.name) %}
  File "/home/myapp/myapp/security.py", line 601, in can_access
    if user.is_anonymous:
AttributeError: 'NoneType' object has no attribute 'is_anonymous'

**Comment by data-infra** [comment]
似乎没有登录。直接进入http://xx.xx/应该会提示跳转到登录，可以无痕模式打开试试，或者清理下缓存

**Comment by tshark** [comment]
回复太速度了，多谢！但无痕模式，清理下缓存，都试了，换了 safari / firefox 还是同样问题

**Comment by data-infra** [comment]
试试 release 2022 09版本，可行么

**Comment by tshark** [comment]
> 
 release 2022 09 试了，同样的问题！

**Comment by ynxu15** [comment]
遇到了同样的问题

**Comment by data-infra** [comment]
单机部署后按照github wiki单机部署后 排查可能存在的问题，首页为/frontend/
